[project]
name = "uv2nix-template"
version = "0.1.0"
description = "A minimal template for Python projects using uv2nix and Nix flakes"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.29.5",
    "jupyter>=1.1.1",
]
